version: "3"

services:

  apiserver:
    build:
      context: .
      dockerfile: ./mods/apiserver/Dockerfile

  routr:
    ports:
      - 4567:4567

  redis:
    ports:
      - 6379:6379

  vault:
    ports:
      - 8200:8200

  fluent:
    ports:
      - 24224:24224
  
  elasticsearch:
    ports:
      - 9200:9200

  minio:
    ports:
      - 9000:9000
