version: "3"

services:

  webui:
    image: fonoster/webui:latest
    ports:
      - 8080:3000
    environment:
      LOGS_LEVEL: ${LOGS_LEVEL}
      WEBUI_APISERVER_ENDPOINT: ${WEBUI_APISERVER_ENDPOINT}
      WEBUI_GITHUB_CLIENT_ID: ${WEBUI_GITHUB_CLIENT_ID}
      WEBUI_GITHUB_CLIENT_SECRET: ${WEBUI_GITHUB_CLIENT_SECRET} 
    logging:
      options:
        tag: fonoster-logs

  apiserver:
    image: fonoster/apiserver:latest
    restart: unless-stopped
    environment:
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
      LOGS_FORMAT: ${LOGS_FORMAT}
      APISERVER_GLOBAL_SIP_DOMAIN: ${APISERVER_GLOBAL_SIP_DOMAIN}
      APISERVER_ROUTR_API_HOST: ${APISERVER_ROUTR_API_HOST}
      APISERVER_ROUTR_API_PORT: ${APISERVER_ROUTR_API_PORT}
      APISERVER_ROUTR_API_USERNAME: ${APISERVER_ROUTR_API_USERNAME}
      APISERVER_ROUTR_API_SECRET: ${APISERVER_ROUTR_API_SECRET}
      APISERVER_MEDIASERVER_SIP_ENDPOINT: ${APISERVER_MEDIASERVER_SIP_ENDPOINT}
      APISERVER_MEDIASERVER_TRUNK: ${APISERVER_MEDIASERVER_TRUNK}
      APISERVER_MEDIASERVER_CONTEXT: ${APISERVER_MEDIASERVER_CONTEXT}
      APISERVER_MEDIASERVER_EXTENSION: ${APISERVER_MEDIASERVER_EXTENSION}
      APISERVER_MEDIASERVER_ARI_INTERNAL_URL: ${APISERVER_MEDIASERVER_ARI_INTERNAL_URL}
      APISERVER_MEDIASERVER_ARI_USERNAME: ${APISERVER_MEDIASERVER_ARI_USERNAME}
      APISERVER_MEDIASERVER_ARI_SECRET: ${APISERVER_MEDIASERVER_ARI_SECRET}
      APISERVER_MEDIASERVER_RECORDINGS_PATH: ${APISERVER_MEDIASERVER_RECORDINGS_PATH}
      APISERVER_JWT_AUTH_ISS: ${APISERVER_JWT_AUTH_ISS}
      APISERVER_JWT_PRIVATE_KEY: ${APISERVER_JWT_PRIVATE_KEY}
      APISERVER_VOICE_URL: ${APISERVER_VOICE_URL}
      APISERVER_VAULT_ADDR: ${APISERVER_VAULT_ADDR}
      APISERVER_VAULT_TOKEN: ${APISERVER_VAULT_TOKEN}
      APISERVER_S3_SERVER_HOST: ${APISERVER_S3_SERVER_HOST}
      APISERVER_S3_SERVER_PORT: ${APISERVER_S3_SERVER_PORT}
      APISERVER_S3_SERVER_USERNAME: ${APISERVER_S3_SERVER_USERNAME}
      APISERVER_S3_SERVER_SECRET: ${APISERVER_S3_SERVER_SECRET}
      APISERVER_S3_SERVER_USE_SSL: ${APISERVER_S3_SERVER_USE_SSL}
      LOGS_AGGREGRATOR_HOST: ${LOGS_AGGREGRATOR_HOST}
      LOGS_AGGREGRATOR_PORT: ${LOGS_AGGREGRATOR_PORT}
    ports:
      - 50052:50052
    logging:
      options:
        tag: fonoster-logs

  routr:
    image: fonoster/routr:1.2.8
    restart: unless-stopped
    environment:
      EXTERN_ADDR: ${DOCKER_HOST_ADDRESS}
      INITIAL_API_SECRET: ${ROUTR_INITIAL_API_SECRET}
      BIND_ADDR: ${ROUTR_BIND_ADDR}
      DATA_SOURCE_PROVIDER: ${ROUTR_DATA_SOURCE_PROVIDER}
      DATA_SOURCE_PARAMETERS: ${ROUTR_DATA_SOURCE_PARAMETERS}
      RECORD_ROUTE: ${ROUTR_RECORD_ROUTE}
      REGISTRAR_INTF: ${ROUTR_REGISTRAR_INTF}
      REST_SERVICE_MIN_THREADS: ${ROUTR_REST_SERVICE_MIN_THREADS}
      REST_SERVICE_MAX_THREADS: ${ROUTR_REST_SERVICE_MAX_THREADS}
      EX_RTP_ENGINE_ENABLED: ${ROUTR_RTPENGINE_ENABLED}
      EX_RTP_ENGINE_PROTO: ${ROUTR_RTPENGINE_PROTO}
      EX_RTP_ENGINE_HOST: ${ROUTR_RTPENGINE_HOST}
      EX_RTP_ENGINE_PORT: ${ROUTR_RTPENGINE_PORT}
      EX_CONVERT_TEL_TO_E164: ${ROUTR_CONVERT_TEL_TO_E164}
      LOGS_DRIVER_HOST: ${LOGS_DRIVER_HOST}
      LOGS_DRIVER_PORT: ${LOGS_DRIVER_PORT}
      JAVA_OPTS: ${ROUTR_JAVA_OPTS}
    expose:
      - 4567
    ports:
      - 5060-5063:5060-5063
      - 5060:5060/udp
    logging:
      options:
        tag: fonoster-logs

  # RTPEngine uses a range of ports to handle RTP traffic. Because exposing a large range of ports 
  # is not possible in Docker, we need to use network_mode: host.
  #
  # Unfortunately, network_mode: host is not supported in Docker for Windows or Mac.
  # In those cases, we need to use a different approach.
  #
  # By default we are opening a small range of ports (30000-30100) to handle RTP traffic.
  # However, this is not enough for production environments.
  #
  # We recommend that when using Linux you use network_mode: host and remove the ports section.
  rtpengine:
    image: fonoster/rtpengine:latest
    restart: unless-stopped
    ports: 
      - 10000-10020:10000-10020/udp
    expose:
      - 8080
    environment:
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      PORT_MIN: 10000
      PORT_MAX: 10100

  mediaserver:
    image: fonoster/mediaserver
    restart: unless-stopped
    environment:
      EXTERN_ADDR: ${DOCKER_HOST_ADDRESS}
      GRPC_ALLOW_INSECURE: ${GRPC_ALLOW_INSECURE}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
      LOGS_FORMAT: ${LOGS_FORMAT}
      EXTERN_PORT: ${MEDIASERVER_EXTERN_PORT}
      APISERVER_ENDPOINT: ${MEDIASERVER_APISERVER_ENDPOINT}
      ARI_EXTERNAL_URL: ${MEDIASERVER_ARI_EXTERNAL_URL}
      ARI_INTERNAL_URL: ${MEDIASERVER_ARI_INTERNAL_URL}
      ARI_USERNAME: ${MEDIASERVER_ARI_USERNAME}
      ARI_SECRET: ${MEDIASERVER_ARI_SECRET}
      SIPPROXY_HOST: ${MEDIASERVER_SIPPROXY_HOST}
      SIPPROXY_PORT: ${MEDIASERVER_SIPPROXY_PORT}
      SIPPROXY_USERNAME: ${MEDIASERVER_SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${MEDIASERVER_SIPPROXY_SECRET}
      RTP_PORT_START: ${MEDIASERVER_RTP_PORT_START}
      RTP_PORT_END: ${MEDIASERVER_RTP_PORT_END}
    volumes:
      - shared:/home/fonoster
    expose:
      - 8080
    logging:
      options:
        tag: fonoster-logs

  voice:
    image: fonoster/rox:latest
    restart: unless-stopped
    expose:
      - 80:3000
      - 3001
    environment:
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
      LOGS_FORMAT: ${LOGS_FORMAT}
    logging:
      options:
        tag: fonoster-logs

  redis:
    image: redis:7.0.8-alpine
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - shared:/data

  vault:
    image: vault:1.13.3
    container_name: vault
    entrypoint: vault server -config=/vault/config/vault.json   
    volumes:
      - shared:/vault/file:rw
      - ./etc/vault.json:/vault/config/vault.json:ro
    cap_add:
      - IPC_LOCK

  fluent:
    image: fonoster/fluent:latest
    restart: unless-stopped
    expose:
      - 24224
    volumes:
      - ./etc/fluent.conf:/fluentd/etc/fluent.conf:ro

  elasticsearch:
    image: elasticsearch:7.17.15
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      - "discovery.type=single-node"
    expose:
      - 9200
    volumes:
      - shared:/usr/share/elasticsearch/data:rw

  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    restart: unless-stopped
    command: minio server /fonoster
    environment:
      MINIO_ACCESS_KEY: ${APISERVER_S3_SERVER_USERNAME}
      MINIO_SECRET_KEY: ${APISERVER_S3_SERVER_SECRET}
    expose:
      - 9000
    volumes:
      - shared:/fonoster  

volumes:
  shared:
