version: '3'

services:

  apiserver:
    image: fonoster/apiserver:latest
    restart: unless-stopped
    environment:
      GLOBAL_SIP_DOMAIN: ${GLOBAL_SIP_DOMAIN}
      DATABASE_URL: ${DATABASE_URL}
      SIPPROXY_HOST: ${DOCKER_HOST_ADDRESS}
      MEDIASERVER_SIP_ENDPOINT: ${MEDIASERVER_SIP_ENDPOINT}
      MEDIASERVER_TRUNK: ${MEDIASERVER_TRUNK}
      MEDIASERVER_CONTEXT: ${MEDIASERVER_CONTEXT}
      MEDIASERVER_EXTENSION: ${MEDIASERVER_EXTENSION}
      MEDIASERVER_ARI_INTERNAL_URL: ${MEDIASERVER_ARI_INTERNAL_URL}
      MEDIASERVER_ARI_USERNAME: ${MEDIASERVER_ARI_USERNAME}
      MEDIASERVER_ARI_SECRET: ${MEDIASERVER_ARI_SECRET}
      MEDIASERVER_RECORDINGS_PATH: ${MEDIASERVER_RECORDINGS_PATH}
      VOICE_URL: ${VOICE_URL}
      VAULT_ADDR: ${VAULT_ADDR}
      SECRETS_POLICY: ${SECRETS_POLICY}
      S3_SERVER_HOST: ${S3_SERVER_HOST}
      S3_SERVER_PORT: ${S3_SERVER_PORT}
      S3_SERVER_USERNAME: ${S3_SERVER_USERNAME}
      S3_SERVER_SECRET: ${S3_SERVER_SECRET}
      LOGS_AGGREGRATOR_HOST: ${LOGS_AGGREGRATOR_HOST}
      LOGS_AGGREGRATOR_PORT: ${LOGS_AGGREGRATOR_PORT}
    ports:
      - 50052:50052

  sipproxy:
    image: fonoster/routr-one:latest
    restart: unless-stopped
    environment:
      EXTERNAL_ADDRS: ${DOCKER_HOST_ADDRESS}
      RTPENGINE_HOST: ${RTPENGINE_HOST}
      RTPENGINE_PORT: ${RTPENGINE_PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres
    expose:
      - 51907
    ports:
      - 51907:51907
      - 5060-5063:5060-5063
      - 5060:5060/udp

  # RTPEngine uses a range of ports to handle RTP traffic. Because exposing a large range of ports 
  # is not possible in Docker, we need to use network_mode: host.
  #
  # Unfortunately, network_mode: host is not supported in Docker for Windows or Mac.
  # In those cases, we need to use a different approach.
  #
  # By default we are opening a small range of ports (30000-30100) to handle RTP traffic.
  # However, this is not enough for production environments.
  #
  # We recommend that when using Linux you use network_mode: host and remove the ports section.
  rtpengine:
    image: fonoster/rtpengine:latest
    restart: unless-stopped
    ports: 
      - 10000-10020:10000-10020/udp
    expose:
      - 8080
    environment:
      PUBLIC_IP: ${DOCKER_HOST_ADDRESS}
      PORT_MIN: 10000
      PORT_MAX: 10100

  mediaserver:
    image: fonoster/mediaserver
    restart: unless-stopped
    environment:
      EXTERN_ADDR: ${DOCKER_HOST_ADDRESS}
      EXTERN_PORT: ${MEDIASERVER_EXTERN_PORT}
      LOGS_LEVEL: ${LOGS_LEVEL}
      APISERVER_ENDPOINT: ${APISERVER_ENDPOINT}
      GRPC_ALLOW_INSECURE: ${GRPC_ALLOW_INSECURE}
      ARI_EXTERNAL_URL: ${MEDIASERVER_ARI_EXTERNAL_URL}
      ARI_INTERNAL_URL: ${MEDIASERVER_ARI_INTERNAL_URL}
      ARI_USERNAME: ${MEDIASERVER_ARI_USERNAME}
      ARI_SECRET: ${MEDIASERVER_ARI_SECRET}
      SIPPROXY_HOST: ${DOCKER_HOST_ADDRESS}
      SIPPROXY_PORT: ${MEDIASERVER_SIPPROXY_PORT}
      SIPPROXY_USERNAME: ${MEDIASERVER_SIPPROXY_USERNAME}
      SIPPROXY_SECRET: ${MEDIASERVER_SIPPROXY_SECRET}
      RTP_PORT_START: ${MEDIASERVER_RTP_PORT_START}
      RTP_PORT_END: ${MEDIASERVER_RTP_PORT_END}
    volumes:
      - shared:/home/fonoster
    expose:
      - 8080

  intents_analyzer:
    image: fonoster/rox:latest
    restart: unless-stopped
    expose:
      - 80:3000
      - 3001
    environment:
      LOGS_LEVEL: ${LOGS_LEVEL}

  postgres:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - TZ=UTC
      - PGTZ=UTC
    expose:
      - 5432
    volumes:
      - shared:/var/lib/postgresql/data

  postgres_init:
    image: fonoster/routr-pgdata-migrations:latest
    restart: "no"
    command: ["npx", "-y", "prisma", "migrate", "deploy"]
    depends_on:
      - postgres
    environment:
      - DATABASE_URL

volumes:
  shared: